app:
  title: Scaffolded Backstage App
  baseUrl: https://localhost:3000  # Frontend stays HTTP
organization:
  name: My Company
backend:
  baseUrl: https://localhost:7007  # Backend uses HTTPS
  listen:
    port: 7007
  https:
    certificate:
      cert:
        $file: ./certs/localhost-cert.pem
      key:
        $file: ./certs/localhost-key.pem
  csp:
    connect-src:
      - '''self'''
      - 'http:'
      - 'https:'
  cors:
    origin: https://localhost:3000
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
proxy: null
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: development
  providers:
    guest: {}
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityName
scaffolder: null
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
  locations:
    - type: file
      target: ../../catalog-info.yaml
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow:
            - Template
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow:
            - User
            - Group
kubernetes: null
permission:
  enabled: true
debug:
  clientId: ${AUTH_GITHUB_CLIENT_ID}
  clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
