app:
  title: Scaffolded Backstage App
  baseUrl: https://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: https://localhost:7007
  listen:
    port: 7007
  https:
    certificate:
      cert:
        $file: ./certs/localhost-cert.pem
      key:
        $file: ./certs/localhost-key.pem
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    asgardeo:
      development:
        metadataUrl: 'https://api.asgardeo.io/t/starkindustriesdemo/.well-known/openid-configuration'
        clientId: reeG8U2HT5NbLOGHbIDQo5Ljfaoa  
        clientSecret: IX9Zg3eycTbJzwJIU4KfTbHPezuhx9WZb20xUysE59ga
        issuer: 'https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token'
        authorizationUrl: 'https://api.asgardeo.io/t/starkindustriesdemo/oauth2/authorize'
        tokenUrl: 'https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token'
        userInfoUrl: 'https://api.asgardeo.io/t/starkindustriesdemo/oauth2/userinfo'
        scope: 'openid profile email'

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

scaffolder:
  defaultAuthor:
    name: Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'

permission:
  enabled: true
