app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000
organization:
  name: My Company
backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src:
      - '''self'''
      - 'http:'
      - 'https:'
  cors:
    origin: http://localhost:3000
    methods:
      - GET
      - HEAD
      - PATCH
      - POST
      - PUT
      - DELETE
    credentials: true
  database:
    client: better-sqlite3
    connection: ':memory:'
integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}
proxy: null
techdocs:
  builder: local
  generator:
    runIn: docker
  publisher:
    type: local
auth:
  environment: development
  providers:
    guest: {}
    # github:
    #   development:
    #     clientId: ${AUTH_GITHUB_CLIENT_ID}
    #     clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
    asgardeo:
      development:
        clientId: ${AUTH_ASGARDEO_CLIENT_ID}
        clientSecret: ${AUTH_ASGARDEO_CLIENT_SECRET}
        issuer: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token
        authorizationUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/authorize
        tokenUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token
        userInfoUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/userinfo
        callbackUrl: http://localhost:7007/api/auth/asgardeo/handler/frame
        scopes:
          - openid
          - profile
        signIn:
          resolvers:
            - resolver: usernameMatchingUserEntityAnnotation
scaffolder: null
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow:
        - Component
        - System
        - API
        - Resource
        - Location
  locations:
    - type: file
      target: ../../catalog-info.yaml
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow:
            - Template
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow:
            - User
            - Group
kubernetes: null
permission:
  enabled: true
debug:
  clientId: ${AUTH_GITHUB_CLIENT_ID}
  clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}
