app:
  title: Scaffolded Backstage App
  baseUrl: http://localhost:3000

organization:
  name: My Company

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
    allowedHeaders: ['Content-Type', 'Authorization', 'X-Requested-With']
  database:
    client: better-sqlite3
    connection: ':memory:'

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowOutsideDevelopment: true
    asgardeo:
      development:
        clientId: 
        clientSecret: 
        issuer: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token
        authorizationUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/authorize
        tokenUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/token
        userInfoUrl: https://api.asgardeo.io/t/starkindustriesdemo/oauth2/userinfo
        callbackUrl: http://localhost:7007/api/auth/asgardeo/handler/frame
        scopes:
          - openid
          - profile
          - email
        signIn:
          resolver:
            [
              {
                resolver: 'emailMatchingUserEntityNameProfile',
                profileTransform: 'asgardeo',
              },
            ]

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: ../../examples/entities.yaml
    - type: file
      target: ../../examples/template/template.yaml
      rules:
        - allow: [Template]
    - type: file
      target: ../../examples/org.yaml
      rules:
        - allow: [User, Group]

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

scaffolder:
  defaultAuthor:
    name: Scaffolder
    email: scaffolder@backstage.io
  defaultCommitMessage: 'Initial commit'

permission:
  enabled: true
